### ISSUE TITLE
uart_rx and uart_tx requirements missing in the file.

### ISSUE THREAD

**Issue by rohithasrk** [Darpha/wtrmrk#1]
The code written [here](https://github.com/Darpha/wtrmrk/blob/master/data_controller.v#L100) requires the uart_rx and uart_tx modules. Please add them

**Comment by Darpha** [comment]
Added in 7ba572cdbf12132953c344917cbcb3ab179df9b9.

I have used these macros on a Spartan 3E FPGA. But these are device specific and may not work for a different device. You can use a platform independent UART module. Refer to the UART manual for the working principle. It should include an 16x8 FIFO buffer, transmitter and receiver modules with control signals described in manual.

Also keep in mind that this design is implemented on an FPGA with very little internal memory (Spartan 3E Basys2 board.). I have used 256x256 grayscale image as the input and 64x64 binary image as the watermark. Internal memory size was around 8 KB, so I had to process the image as separate blocks. You can modify the design depending on your available memory.
